title: Let's Rock Guy's!!!
author: ironman
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's an example of how magic happen in internet.
  Start exploring things and see magic.

# social links
twitter_username: notwitter # DO NOT include the @ character, or else the build will fail!
github_username:  awesomesonu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
